###############################################################################
#                          Generated on lib/Docker.io                          #
###############################################################################
version: "3.1"

volumes:

  mysql:

services:

    redis:
      image: redis:alpine
      container_name: redis

    mysql:
      image: mysql:8.0
      container_name: mysql
      working_dir: /application
      volumes:
        - mysql:/var/lib/mysql
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dev
        - MYSQL_DATABASE=continuity
        - MYSQL_USER=dev
        - MYSQL_PASSWORD=dev
      ports:
        - "3306:3306"

    elasticsearch:
      image: elasticsearch:6.5.4
      container_name: elasticsearch

    nginx:
      image: nginx:alpine
      container_name: webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./lib/Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "31415:80"

    php-fpm:
      build: lib/docker/php-fpm
      container_name: php-fpm
      working_dir: /application
      ports:
        - "9000:9000"
      volumes:
        - .:/application
        - ./lib/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini




